CREATE TABLE idt_contrato
(
  idt_contrato_id character varying(32) NOT NULL,
  atnorh_cargo_id character varying(32),
  ad_client_id character varying(32) NOT NULL,
  ad_org_id character varying(32) NOT NULL,
  c_doctype_id character varying(32) NOT NULL,
  c_bpartner_id character varying(32) NOT NULL,
  c_currency_id character varying(32), 
  fin_financial_account_id character varying(32),
  fin_paymentmethod_id character varying(32),
  ne_area_empresa_id character varying(32),
  createdby character varying(32) NOT NULL,
  updatedby character varying(32) NOT NULL,
  isactive character(1) NOT NULL DEFAULT 'Y'::bpchar,
  created timestamp without time zone NOT NULL DEFAULT now(),  
  updated timestamp without time zone NOT NULL DEFAULT now(),  
  fecha_inicio timestamp without time zone NOT NULL,
  fecha_fin timestamp without time zone,
  documentno character varying(40) NOT NULL,  
  salario numeric NOT NULL,  
  tipo_contrato character varying(60) NOT NULL,
  pagofondoreserva character(1) NOT NULL,  
  is_impuesto_asumido character(1),
  aplica_utilidad character(1) DEFAULT 'Y'::bpchar,
  em_ne_sissalnet character varying(60),  
  em_ne_motivo_salida character varying(60),
  em_ne_is_jornada_parcial character(1) DEFAULT 'N'::bpchar,
  em_ne_num_horas_parciales numeric,
  em_ne_vacacion_prop numeric(10,2),
  em_ne_vacacion_tom numeric(10,2),
  em_ne_vacacion_res numeric(10,2),
  em_ne_region character varying(60),
  em_ne_observaciones character varying(255),
  
  )